#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArenaSequencer

#include "Basic.hpp"

#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ArenaSequencer.BP_ArenaSequencer_C
// 0x0000 (0x01A8 - 0x01A8)
class UBP_ArenaSequencer_C final : public UPalArenaSequencer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ArenaSequencer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ArenaSequencer_C")
	}
	static class UBP_ArenaSequencer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ArenaSequencer_C>();
	}
};
DUMPER7_ASSERTS_UBP_ArenaSequencer_C;

}

