#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionLogoutPlayer

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ActionLogoutPlayer.BP_ActionLogoutPlayer_C.ExecuteUbergraph_BP_ActionLogoutPlayer
// 0x0010 (0x0010 - 0x0000)
struct BP_ActionLogoutPlayer_C_ExecuteUbergraph_BP_ActionLogoutPlayer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ActionLogoutPlayer_C_ExecuteUbergraph_BP_ActionLogoutPlayer;

// Function BP_ActionLogoutPlayer.BP_ActionLogoutPlayer_C.SetDisableCollision
// 0x0020 (0x0020 - 0x0000)
struct BP_ActionLogoutPlayer_C_SetDisableCollision final
{
public:
	bool                                          isDisable;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalPlayerCharacter*                    K2Node_DynamicCast_AsPal_Player_Character;         // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ActionLogoutPlayer_C_SetDisableCollision;

}

