#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionMining_Player

#include "Basic.hpp"

#include "BP_ActionMining_Player_classes.hpp"
#include "BP_ActionMining_Player_parameters.hpp"


namespace SDK
{

// Function BP_ActionMining_Player.BP_ActionMining_Player_C.ExecuteUbergraph_BP_ActionMining_Player
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionMining_Player_C::ExecuteUbergraph_BP_ActionMining_Player(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "ExecuteUbergraph_BP_ActionMining_Player");

	Params::BP_ActionMining_Player_C_ExecuteUbergraph_BP_ActionMining_Player Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.GetDetectableNotifyNames
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FName>*                    Array                                                  (Parm, OutParm)

void UBP_ActionMining_Player_C::GetDetectableNotifyNames(TArray<class FName>* Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "GetDetectableNotifyNames");

	Params::BP_ActionMining_Player_C_GetDetectableNotifyNames Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Array != nullptr)
		*Array = std::move(Parms.Array);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.OnBeginAction
// (Event, Public, BlueprintEvent)

void UBP_ActionMining_Player_C::OnBeginAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "OnBeginAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.OnBeginAnimNotify
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     Montage                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionMining_Player_C::OnBeginAnimNotify(class UAnimMontage* Montage, class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "OnBeginAnimNotify");

	Params::BP_ActionMining_Player_C_OnBeginAnimNotify Parms{};

	Parms.Montage = Montage;
	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.OnEndAction
// (Event, Public, BlueprintEvent)

void UBP_ActionMining_Player_C::OnEndAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "OnEndAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.RequestDamageTargetObject
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionMining_Player_C::RequestDamageTargetObject()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "RequestDamageTargetObject");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.SetHiddenAttachWeapon
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isHidden                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionMining_Player_C::SetHiddenAttachWeapon(bool isHidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "SetHiddenAttachWeapon");

	Params::BP_ActionMining_Player_C_SetHiddenAttachWeapon Parms{};

	Parms.isHidden = isHidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionMining_Player.BP_ActionMining_Player_C.TriggerWorkActionAttackIfNeed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UAnimMontage*               Montage                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FName                             SectionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionMining_Player_C::TriggerWorkActionAttackIfNeed(const class UAnimMontage* Montage, class FName SectionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionMining_Player_C", "TriggerWorkActionAttackIfNeed");

	Params::BP_ActionMining_Player_C_TriggerWorkActionAttackIfNeed Parms{};

	Parms.Montage = Montage;
	Parms.SectionName = SectionName;

	UObject::ProcessEvent(Func, &Parms);
}

}

