#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIAction_NPC_Combat_Melee

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "EPal_NPC_CombatMeleeState_structs.hpp"
#include "BP_AIAction_NPC_CombatBase_classes.hpp"
#include "AIModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIAction_NPC_Combat_Melee.BP_AIAction_NPC_Combat_Melee_C
// 0x0088 (0x0250 - 0x01C8)
class UBP_AIAction_NPC_Combat_Melee_C : public UBP_AIAction_NPC_CombatBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_AIAction_NPC_Combat_Melee_C;     // 0x01C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	EPal_NPC_CombatMeleeState                     CurrentState;                                      // 0x01D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        ConstAttackStartRange;                             // 0x01D8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsStopTick;                                        // 0x01E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	uint8                                         Pad_1E1[0x7];                                      // 0x01E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        ConstNearAttackRange;                              // 0x01E8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Timer;                                             // 0x01F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	TMap<EPal_NPC_CombatMeleeState, class UClass*> StateMap;                                         // 0x01F8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        BackwardMiniTime;                                  // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActionFinished(class APawn* ControlledPawn, EPawnActionResult WithResult);
	void ActionPause(class APawn* ControlledPawn);
	void ActionResume(class APawn* ControlledPawn);
	void ActionStart(class APawn* ControlledPawn);
	void ActionTick(class APawn* ControlledPawn, float DeltaSeconds);
	void AddMeleeCombatState(EPal_NPC_CombatMeleeState MeleeState);
	void AddTimer(double* CurrentTime);
	void Change_NextState(EPal_NPC_CombatMeleeState Next);
	void ExecuteUbergraph_BP_AIAction_NPC_Combat_Melee(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AIAction_NPC_Combat_Melee_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AIAction_NPC_Combat_Melee_C")
	}
	static class UBP_AIAction_NPC_Combat_Melee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AIAction_NPC_Combat_Melee_C>();
	}
};
DUMPER7_ASSERTS_UBP_AIAction_NPC_Combat_Melee_C;

}

