#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BuildObject_WeaponFactory_Dirty_01

#include "Basic.hpp"

#include "BP_BuildObject_WeaponFactoryBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BuildObject_WeaponFactory_Dirty_01.BP_BuildObject_WeaponFactory_Dirty_01_C
// 0x0010 (0x07B0 - 0x07A0)
class ABP_BuildObject_WeaponFactory_Dirty_01_C final : public ABP_BuildObject_WeaponFactoryBase_C
{
public:
	class USceneComponent*                        Root_0;                                            // 0x07A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BuildObject_WeaponFactory_Dirty_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BuildObject_WeaponFactory_Dirty_01_C")
	}
	static class ABP_BuildObject_WeaponFactory_Dirty_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BuildObject_WeaponFactory_Dirty_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_BuildObject_WeaponFactory_Dirty_01_C;

}

