#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DungeonFixedEntrance_forest_2

#include "Basic.hpp"

#include "BP_DungeonFixedEntrance_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DungeonFixedEntrance_forest_2.BP_DungeonFixedEntrance_forest_2_C
// 0x0008 (0x0368 - 0x0360)
class ABP_DungeonFixedEntrance_forest_2_C final : public ABP_DungeonFixedEntrance_C
{
public:
	class UNiagaraComponent*                      Niagara;                                           // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DungeonFixedEntrance_forest_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DungeonFixedEntrance_forest_2_C")
	}
	static class ABP_DungeonFixedEntrance_forest_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DungeonFixedEntrance_forest_2_C>();
	}
};
DUMPER7_ASSERTS_ABP_DungeonFixedEntrance_forest_2_C;

}

