#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnemyCampTreasureBoxSpawnerComponent

#include "Basic.hpp"

#include "BP_EnemyCampTreasureBoxSpawnerComponent_classes.hpp"
#include "BP_EnemyCampTreasureBoxSpawnerComponent_parameters.hpp"


namespace SDK
{

// Function BP_EnemyCampTreasureBoxSpawnerComponent.BP_EnemyCampTreasureBoxSpawnerComponent_C.GetCampSpawnerName
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FName                             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class FName UBP_EnemyCampTreasureBoxSpawnerComponent_C::GetCampSpawnerName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnemyCampTreasureBoxSpawnerComponent_C", "GetCampSpawnerName");

	Params::BP_EnemyCampTreasureBoxSpawnerComponent_C_GetCampSpawnerName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

