#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MainQuestBlock_TutorialStart

#include "Basic.hpp"

#include "BP_MainQuestBlock_TutorialStart_classes.hpp"
#include "BP_MainQuestBlock_TutorialStart_parameters.hpp"


namespace SDK
{

// Function BP_MainQuestBlock_TutorialStart.BP_MainQuestBlock_TutorialStart_C.GetDescriptionText
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText*                            OutText                                                (Parm, OutParm)

void UBP_MainQuestBlock_TutorialStart_C::GetDescriptionText(class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MainQuestBlock_TutorialStart_C", "GetDescriptionText");

	Params::BP_MainQuestBlock_TutorialStart_C_GetDescriptionText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);
}

}

