#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalPlayerManager

#include "Basic.hpp"

#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalPlayerManager.BP_PalPlayerManager_C
// 0x0000 (0x01B0 - 0x01B0)
class UBP_PalPlayerManager_C final : public UPalPlayerManager
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PalPlayerManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PalPlayerManager_C")
	}
	static class UBP_PalPlayerManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PalPlayerManager_C>();
	}
};
DUMPER7_ASSERTS_UBP_PalPlayerManager_C;

}

