#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast.BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast_C.ExecuteUbergraph_BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast
// 0x0028 (0x0028 - 0x0000)
struct BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast_C_ExecuteUbergraph_BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast_C_ExecuteUbergraph_BP_SkillEffect_Unique_WhiteDeer_HolyPillar_Blast;

}

