#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail

#include "Basic.hpp"

#include "BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_classes.hpp"
#include "BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_parameters.hpp"


namespace SDK
{

// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.ExecuteUbergraph_BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::ExecuteUbergraph_BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "ExecuteUbergraph_BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_ExecuteUbergraph_BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.FadeOutEffect
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaSecond                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::FadeOutEffect(double DeltaSecond)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "FadeOutEffect");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_FadeOutEffect Parms{};

	Parms.DeltaSecond = DeltaSecond;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.OnLifeTime
// (BlueprintCallable, BlueprintEvent)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::OnLifeTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "OnLifeTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "ReceiveTick");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.SetFixedRotation
// (BlueprintCallable, BlueprintEvent)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::SetFixedRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "SetFixedRotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.SetLifeTimer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Duration                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::SetLifeTimer(double Duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "SetLifeTimer");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_SetLifeTimer Parms{};

	Parms.Duration = Duration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.SetRootAction
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_Action_Unique_DarkMechaDragon_WarpComet_C*action                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::SetRootAction(class UBP_Action_Unique_DarkMechaDragon_WarpComet_C* action)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "SetRootAction");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_SetRootAction Parms{};

	Parms.action = action;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.SetRotation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  NewRotation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::SetRotation(const struct FRotator& NewRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "SetRotation");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_SetRotation Parms{};

	Parms.NewRotation = std::move(NewRotation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail.BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C.SetScale
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Scale                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C::SetScale(double Scale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C", "SetScale");

	Params::BP_SkillEffect_Unique_DarkMechaDragon_WarpComet_TackleTrail_C_SetScale Parms{};

	Parms.Scale = Scale;

	UObject::ProcessEvent(Func, &Parms);
}

}

