#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_SandTwister

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_SkillEffectBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SkillEffect_SandTwister.BP_SkillEffect_SandTwister_C
// 0x0088 (0x04B8 - 0x0430)
class ABP_SkillEffect_SandTwister_C final : public ABP_SkillEffectBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SkillEffect_SandTwister_C;       // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        TargetTwisterLifeTime;                             // 0x0438(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumAroundTwister;                                  // 0x0440(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_444[0x4];                                      // 0x0444(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AroundTwisterSpawnRadius;                          // 0x0448(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AroundTwisterShakeLength;                          // 0x0450(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AroundTwisterShakeSpeed;                           // 0x0458(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AroundTwisterLifeTime;                             // 0x0460(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        AroundTwisterSpeed;                                // 0x0468(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AroundTwisterIsClockwise;                          // 0x0470(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_471[0x7];                                      // 0x0471(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AroundTwisterSpawnAngleOffset;                     // 0x0478(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_SkillEffect_SandTwister_Tornado_C*> AroundTornados;                             // 0x0480(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<double>                                AroundTwisterShakeTimers;                          // 0x0490(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        OmenLifeTime;                                      // 0x04A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_SkillEffect_SandTwister_Omen_C*> Omens;                                         // 0x04A8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

public:
	void StartSpawn();
	void SpawnTornadoOmen(const struct FVector& Location, class ABP_SkillEffect_SandTwister_Omen_C** NewParam);
	void SpawnTargetTornadoInternal();
	void SpawnAroundTornadoInternal();
	void Spawn_Tornado(const struct FVector& Location, double LifeTime_0, class ABP_SkillEffect_SandTwister_Tornado_C** SkillEffect);
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_BP_SkillEffect_SandTwister(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SkillEffect_SandTwister_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SkillEffect_SandTwister_C")
	}
	static class ABP_SkillEffect_SandTwister_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SkillEffect_SandTwister_C>();
	}
};
DUMPER7_ASSERTS_ABP_SkillEffect_SandTwister_C;

}

