#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueAction_GhostDragon_PhosphorousBeam

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Engine_structs.hpp"
#include "BP_ActionUniqueAttackBase_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UniqueAction_GhostDragon_PhosphorousBeam.BP_UniqueAction_GhostDragon_PhosphorousBeam_C
// 0x0050 (0x02F0 - 0x02A0)
class UBP_UniqueAction_GhostDragon_PhosphorousBeam_C final : public UBP_ActionUniqueAttackBase_C
{
public:
	uint8                                         Pad_294[0x4];                                      // 0x0294(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_UniqueAction_GhostDragon_PhosphorousBeam_C; // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<struct FReserveMontage>                Montage_List;                                      // 0x02A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         ChargeTime;                                        // 0x02B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B4[0x4];                                      // 0x02B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CurrentTimer;                                      // 0x02B8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         AttackMontageTime;                                 // 0x02C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableRotate;                                      // 0x02C4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnLevel;                                       // 0x02C5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C6[0x2];                                      // 0x02C6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_UniqueSkillEffect_GhostDragon_PhosphorousBeam_Beam_C* BeamEffect;                      // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        MaxBeamTime;                                       // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           BeamTimer;                                         // 0x02D8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        BeamMaxLength;                                     // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActAttack();
	void ActEnd();
	void ExecuteUbergraph_BP_UniqueAction_GhostDragon_PhosphorousBeam(int32 EntryPoint);
	void Explode();
	void GetRotation(double DeltaTime, bool NoInterp, struct FRotator* Rotation);
	void OnBeginAction();
	void OnBlendOut_094B0C6F4532E241D0A3D0B9AAD75489(class FName NotifyName);
	void OnCompleted_094B0C6F4532E241D0A3D0B9AAD75489(class FName NotifyName);
	void OnEndAction();
	void OnInterrupted_094B0C6F4532E241D0A3D0B9AAD75489(class FName NotifyName);
	void OnMontageEnd(class UAnimMontage* Montage, bool bInterrupted);
	void OnNotifyBegin_094B0C6F4532E241D0A3D0B9AAD75489(class FName NotifyName);
	void OnNotifyEnd_094B0C6F4532E241D0A3D0B9AAD75489(class FName NotifyName);
	void TickAction(float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UniqueAction_GhostDragon_PhosphorousBeam_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UniqueAction_GhostDragon_PhosphorousBeam_C")
	}
	static class UBP_UniqueAction_GhostDragon_PhosphorousBeam_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UniqueAction_GhostDragon_PhosphorousBeam_C>();
	}
};
DUMPER7_ASSERTS_UBP_UniqueAction_GhostDragon_PhosphorousBeam_C;

}

