#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager

#include "Basic.hpp"

#include "BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_classes.hpp"
#include "BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_parameters.hpp"


namespace SDK
{

// Function BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager.BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C.ActPillar
// (BlueprintCallable, BlueprintEvent)

void ABP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C::ActPillar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C", "ActPillar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager.BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C.ExecuteUbergraph_BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C::ExecuteUbergraph_BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C", "ExecuteUbergraph_BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager");

	Params::BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C_ExecuteUbergraph_BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager.BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager.BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C.SearchTarget
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C::SearchTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C", "SearchTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager.BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C.SetScale
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Scale                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C::SetScale(double Scale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C", "SetScale");

	Params::BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C_SetScale Parms{};

	Parms.Scale = Scale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager.BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C.SpawnPillar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C::SpawnPillar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueSkillEffect_LegendDeer_WarpPillarBurst_PillarManager_C", "SpawnPillar");

	UObject::ProcessEvent(Func, nullptr);
}

}

