#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PalWazaBulletEmiiterOverlap_FireBall

#include "Basic.hpp"

#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PalWazaBulletEmiiterOverlap_FireBall.PalWazaBulletEmiiterOverlap_FireBall_C
// 0x0000 (0x0028 - 0x0028)
class UPalWazaBulletEmiiterOverlap_FireBall_C final : public UPalWazaBulletEmiiterOverlapBase
{
public:
	void GetBulletEmiiterOverlapSphere(TArray<struct FPalWazaBulletEmiiterOverlapSphere>* Spheres);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PalWazaBulletEmiiterOverlap_FireBall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PalWazaBulletEmiiterOverlap_FireBall_C")
	}
	static class UPalWazaBulletEmiiterOverlap_FireBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPalWazaBulletEmiiterOverlap_FireBall_C>();
	}
};
DUMPER7_ASSERTS_UPalWazaBulletEmiiterOverlap_FireBall_C;

}

