#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenuConstruction_ItemSlot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_IngameMenuConstruction_ItemSlot.WBP_IngameMenuConstruction_ItemSlot_C
// 0x0110 (0x0388 - 0x0278)
class UWBP_IngameMenuConstruction_ItemSlot_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anm_OnToOff_WithoutText;                           // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_LtoS;                                          // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_OnToOff;                                       // 0x0290(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_2;                                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_Lock;                                  // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_BuildObjectName;                              // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_Label;                                        // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_NewDot_C*                 WBP_MainMenu_NewDot;                               // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalCommonNewMark_0_C*              WBP_PalCommonNewMark_0;                            // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FPalBuildObjectData                    BuildObjectData;                                   // 0x02D0(0x0098)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FDataTableRowHandle                    NotEnoughMaterialMsgID;                            // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    NoBlueprintlMsgID;                                 // 0x0378(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void Setup(const struct FPalBuildObjectData& BuildObjectData_0);
	void SetNewIconVisibility(bool Visable);
	void ExecuteUbergraph_WBP_IngameMenuConstruction_ItemSlot(int32 EntryPoint);
	void DisableTextForDeck();
	void Construct();
	void AnmEvent_Small();
	void AnmEvent_CannotBuild_NoText();
	void AnmEvent_CannotBuild_NotEnoughMaterials();
	void AnmEvent_CannotBuild_NoBlueprint();

	struct FVector2D GetCanvasSize() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_IngameMenuConstruction_ItemSlot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_IngameMenuConstruction_ItemSlot_C")
	}
	static class UWBP_IngameMenuConstruction_ItemSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_IngameMenuConstruction_ItemSlot_C>();
	}
};
DUMPER7_ASSERTS_UWBP_IngameMenuConstruction_ItemSlot_C;

}

