#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WarningEvent_WaveClear_Mark

#include "Basic.hpp"

#include "WBP_WarningEvent_WaveClear_Mark_classes.hpp"
#include "WBP_WarningEvent_WaveClear_Mark_parameters.hpp"


namespace SDK
{

// Function WBP_WarningEvent_WaveClear_Mark.WBP_WarningEvent_WaveClear_Mark_C.ExecuteUbergraph_WBP_WarningEvent_WaveClear_Mark
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_WarningEvent_WaveClear_Mark_C::ExecuteUbergraph_WBP_WarningEvent_WaveClear_Mark(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WarningEvent_WaveClear_Mark_C", "ExecuteUbergraph_WBP_WarningEvent_WaveClear_Mark");

	Params::WBP_WarningEvent_WaveClear_Mark_C_ExecuteUbergraph_WBP_WarningEvent_WaveClear_Mark Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_WarningEvent_WaveClear_Mark.WBP_WarningEvent_WaveClear_Mark_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_WarningEvent_WaveClear_Mark_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WarningEvent_WaveClear_Mark_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WarningEvent_WaveClear_Mark.WBP_WarningEvent_WaveClear_Mark_C.AnmEvent_UncheckInstant
// (BlueprintCallable, BlueprintEvent)

void UWBP_WarningEvent_WaveClear_Mark_C::AnmEvent_UncheckInstant()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WarningEvent_WaveClear_Mark_C", "AnmEvent_UncheckInstant");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WarningEvent_WaveClear_Mark.WBP_WarningEvent_WaveClear_Mark_C.AnmEvent_CheckInstant
// (BlueprintCallable, BlueprintEvent)

void UWBP_WarningEvent_WaveClear_Mark_C::AnmEvent_CheckInstant()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WarningEvent_WaveClear_Mark_C", "AnmEvent_CheckInstant");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_WarningEvent_WaveClear_Mark.WBP_WarningEvent_WaveClear_Mark_C.AnmEvent_Check
// (BlueprintCallable, BlueprintEvent)

void UWBP_WarningEvent_WaveClear_Mark_C::AnmEvent_Check()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WarningEvent_WaveClear_Mark_C", "AnmEvent_Check");

	UObject::ProcessEvent(Func, nullptr);
}

}

