#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Expedition_PalPowerPopup

#include "Basic.hpp"

#include "WBP_Expedition_PalPowerPopup_classes.hpp"
#include "WBP_Expedition_PalPowerPopup_parameters.hpp"


namespace SDK
{

// Function WBP_Expedition_PalPowerPopup.WBP_Expedition_PalPowerPopup_C.SetPower
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Power                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Expedition_PalPowerPopup_C::SetPower(int32 Power)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Expedition_PalPowerPopup_C", "SetPower");

	Params::WBP_Expedition_PalPowerPopup_C_SetPower Parms{};

	Parms.Power = Power;

	UObject::ProcessEvent(Func, &Parms);
}

}

