#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PlayerInputGuard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayerInputGuard.WBP_PlayerInputGuard_C
// 0x0008 (0x0458 - 0x0450)
class UWBP_PlayerInputGuard_C final : public UPalUIInputGuard
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnSetup();
	void ExecuteUbergraph_WBP_PlayerInputGuard(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PlayerInputGuard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PlayerInputGuard_C")
	}
	static class UWBP_PlayerInputGuard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayerInputGuard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PlayerInputGuard_C;

}

