#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TutorialPopup_ForDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TutorialPopup_ForDisplay.WBP_TutorialPopup_ForDisplay_C
// 0x0010 (0x0488 - 0x0478)
class UWBP_TutorialPopup_ForDisplay_C final : public UPalUserWidgetOverlayUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0478(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_CommonTutorialPopup_C*             WBP_CommonTutorialPopup;                           // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnSetup();
	void ExecuteUbergraph_WBP_TutorialPopup_ForDisplay(int32 EntryPoint);
	void BndEvt__WBP_TutorialPopup_ForDisplay_WBP_CommonTutorialPopup_K2Node_ComponentBoundEvent_0_OnClickedYes__DelegateSignature();

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TutorialPopup_ForDisplay_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TutorialPopup_ForDisplay_C")
	}
	static class UWBP_TutorialPopup_ForDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TutorialPopup_ForDisplay_C>();
	}
};
DUMPER7_ASSERTS_UWBP_TutorialPopup_ForDisplay_C;

}

