#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionStep_New_Right

#include "Basic.hpp"

#include "BP_ActionStepBase_New_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionStep_New_Right.BP_ActionStep_New_Right_C
// 0x0000 (0x0290 - 0x0290)
class UBP_ActionStep_New_Right_C final : public UBP_ActionStepBase_New_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionStep_New_Right_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionStep_New_Right_C")
	}
	static class UBP_ActionStep_New_Right_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionStep_New_Right_C>();
	}
};
DUMPER7_ASSERTS_UBP_ActionStep_New_Right_C;

}

