#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPCWeaponGenerator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPCWeaponGenerator.BP_NPCWeaponGenerator_C
// 0x0008 (0x00F0 - 0x00E8)
class UBP_NPCWeaponGenerator_C final : public UPalNPCWeaponGenerator
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_NPCWeaponGenerator(int32 EntryPoint);
	void OnSpawnEvent(class APalWeaponBase* WeaponActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPCWeaponGenerator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPCWeaponGenerator_C")
	}
	static class UBP_NPCWeaponGenerator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NPCWeaponGenerator_C>();
	}
};
DUMPER7_ASSERTS_UBP_NPCWeaponGenerator_C;

}

