#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalSphere_Tera

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_PalSphere_Tera.BP_PalSphere_Tera_C.GetThrowObjectClass
// 0x0008 (0x0008 - 0x0000)
struct BP_PalSphere_Tera_C_GetThrowObjectClass final
{
public:
	class UClass*                                 ThrowObject;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_PalSphere_Tera_C_GetThrowObjectClass;

}

