#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Status_JumpingFrog

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Status_JumpingFrog.BP_Status_JumpingFrog_C
// 0x0020 (0x00F0 - 0x00D0)
class UBP_Status_JumpingFrog_C : public UPalStatusJumpingFrog
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	EPalVisualEffectID                            Visual_Effect_ID;                                  // 0x00D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      Effect;                                            // 0x00E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowEffect;                                        // 0x00E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void CreateEffect();
	void DebugOnBegin();
	void DebugOnEnd();
	void DebugOnTick();
	void DeleteEffect();
	void ExecuteUbergraph_BP_Status_JumpingFrog(int32 EntryPoint);
	void OnBeginSomeStatus();
	void OnBeginStatus();
	void OnChangeSliding(class UPalCharacterMovementComponent* Component, bool IsInSliding);
	void OnEndStatus();
	void OnInactive();
	void OnJump(class UPalCharacterMovementComponent* Component);
	void OnLanded(class UPalCharacterMovementComponent* Component, const struct FHitResult& Hit);
	void OnMovementModeChanged(class UPalCharacterMovementComponent* Component, EMovementMode prevMode, EMovementMode newMode, EPalCharacterMovementCustomMode PrevCustomMode, EPalCharacterMovementCustomMode NewCustomMode);
	void StartPassiveSkills();
	void TickStatus(float DeltaTime);
	void UpdateEffect();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Status_JumpingFrog_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Status_JumpingFrog_C")
	}
	static class UBP_Status_JumpingFrog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Status_JumpingFrog_C>();
	}
};
DUMPER7_ASSERTS_UBP_Status_JumpingFrog_C;

}

