#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Status_AcidDamage

#include "Basic.hpp"

#include "BP_Status_AcidDamage_classes.hpp"
#include "BP_Status_AcidDamage_parameters.hpp"


namespace SDK
{

// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.AcidDamage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_Status_AcidDamage_C::AcidDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "AcidDamage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.ExecuteUbergraph_BP_Status_AcidDamage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Status_AcidDamage_C::ExecuteUbergraph_BP_Status_AcidDamage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "ExecuteUbergraph_BP_Status_AcidDamage");

	Params::BP_Status_AcidDamage_C_ExecuteUbergraph_BP_Status_AcidDamage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.GetAcidDamage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_Status_AcidDamage_C::GetAcidDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "GetAcidDamage");

	Params::BP_Status_AcidDamage_C_GetAcidDamage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.OnBeginStatus
// (Event, Public, BlueprintEvent)

void UBP_Status_AcidDamage_C::OnBeginStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "OnBeginStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.OnCompleteInitializeParameter
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APalCharacter*                    InCharacter                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_Status_AcidDamage_C::OnCompleteInitializeParameter(class APalCharacter* InCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "OnCompleteInitializeParameter");

	Params::BP_Status_AcidDamage_C_OnCompleteInitializeParameter Parms{};

	Parms.InCharacter = InCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.OnEndStatus
// (Event, Public, BlueprintEvent)

void UBP_Status_AcidDamage_C::OnEndStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "OnEndStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Status_AcidDamage_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Status_AcidDamage.BP_Status_AcidDamage_C.TickStatus
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Status_AcidDamage_C::TickStatus(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Status_AcidDamage_C", "TickStatus");

	Params::BP_Status_AcidDamage_C_TickStatus Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

