#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueRideWeapon_Minigun

#include "Basic.hpp"

#include "BP_UniqueRideWeapon_Minigun_classes.hpp"
#include "BP_UniqueRideWeapon_Minigun_parameters.hpp"


namespace SDK
{

// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.ExecuteUbergraph_BP_UniqueRideWeapon_Minigun
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UniqueRideWeapon_Minigun_C::ExecuteUbergraph_BP_UniqueRideWeapon_Minigun(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "ExecuteUbergraph_BP_UniqueRideWeapon_Minigun");

	Params::BP_UniqueRideWeapon_Minigun_C_ExecuteUbergraph_BP_UniqueRideWeapon_Minigun Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetAllMeshComponent
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UMeshComponent*>*          OutMesh                                                (Parm, OutParm, ContainsInstancedReference)

void ABP_UniqueRideWeapon_Minigun_C::GetAllMeshComponent(TArray<class UMeshComponent*>* OutMesh)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetAllMeshComponent");

	Params::BP_UniqueRideWeapon_Minigun_C_GetAllMeshComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutMesh != nullptr)
		*OutMesh = std::move(Parms.OutMesh);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetAmmoClass
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class AActor>               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class AActor> ABP_UniqueRideWeapon_Minigun_C::GetAmmoClass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetAmmoClass");

	Params::BP_UniqueRideWeapon_Minigun_C_GetAmmoClass Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetAmmoEjectTransform
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform                       ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FTransform ABP_UniqueRideWeapon_Minigun_C::GetAmmoEjectTransform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetAmmoEjectTransform");

	Params::BP_UniqueRideWeapon_Minigun_C_GetAmmoEjectTransform Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetBulletClass
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TSubclassOf<class APalBullet>           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class APalBullet> ABP_UniqueRideWeapon_Minigun_C::GetBulletClass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetBulletClass");

	Params::BP_UniqueRideWeapon_Minigun_C_GetBulletClass Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetBulrAngle
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ABP_UniqueRideWeapon_Minigun_C::GetBulrAngle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetBulrAngle");

	Params::BP_UniqueRideWeapon_Minigun_C_GetBulrAngle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetMuzzleEffect
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UNiagaraSystem*                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UNiagaraSystem* ABP_UniqueRideWeapon_Minigun_C::GetMuzzleEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetMuzzleEffect");

	Params::BP_UniqueRideWeapon_Minigun_C_GetMuzzleEffect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetMuzzleLocation
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector ABP_UniqueRideWeapon_Minigun_C::GetMuzzleLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetMuzzleLocation");

	Params::BP_UniqueRideWeapon_Minigun_C_GetMuzzleLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetMuzzleRotation
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

struct FRotator ABP_UniqueRideWeapon_Minigun_C::GetMuzzleRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetMuzzleRotation");

	Params::BP_UniqueRideWeapon_Minigun_C_GetMuzzleRotation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.GetShootInterval
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double*                                 Time                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UniqueRideWeapon_Minigun_C::GetShootInterval(double* Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "GetShootInterval");

	Params::BP_UniqueRideWeapon_Minigun_C_GetShootInterval Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Time != nullptr)
		*Time = Parms.Time;
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.OnPlayFireLoopSound
// (BlueprintCallable, BlueprintEvent)

void ABP_UniqueRideWeapon_Minigun_C::OnPlayFireLoopSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "OnPlayFireLoopSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.OnPullTrigger
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_UniqueRideWeapon_Minigun_C::OnPullTrigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "OnPullTrigger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.OnReleaseTrigger
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bCanShootOnRelease                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UniqueRideWeapon_Minigun_C::OnReleaseTrigger(bool bCanShootOnRelease)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "OnReleaseTrigger");

	Params::BP_UniqueRideWeapon_Minigun_C_OnReleaseTrigger Parms{};

	Parms.bCanShootOnRelease = bCanShootOnRelease;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.PlayFireLoopSound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_UniqueRideWeapon_Minigun_C::PlayFireLoopSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "PlayFireLoopSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UniqueRideWeapon_Minigun_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "ReceiveTick");

	Params::BP_UniqueRideWeapon_Minigun_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.ShootBulletBP
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_UniqueRideWeapon_Minigun_C::ShootBulletBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "ShootBulletBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UniqueRideWeapon_Minigun.BP_UniqueRideWeapon_Minigun_C.StopFireLoopSound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_UniqueRideWeapon_Minigun_C::StopFireLoopSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UniqueRideWeapon_Minigun_C", "StopFireLoopSound");

	UObject::ProcessEvent(Func, nullptr);
}

}

