#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SCML_UI_ButtonArrow

#include "Basic.hpp"

#include "SCML_UI_ButtonArrow_classes.hpp"
#include "SCML_UI_ButtonArrow_parameters.hpp"


namespace SDK
{

// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.SetUnselect
// (Public, BlueprintCallable, BlueprintEvent)

void USCML_UI_ButtonArrow_C::SetUnselect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "SetUnselect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.SetSelect
// (Public, BlueprintCallable, BlueprintEvent)

void USCML_UI_ButtonArrow_C::SetSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "SetSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.SetInactive
// (Public, BlueprintCallable, BlueprintEvent)

void USCML_UI_ButtonArrow_C::SetInactive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "SetInactive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.SetActive
// (Public, BlueprintCallable, BlueprintEvent)

void USCML_UI_ButtonArrow_C::SetActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "SetActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USCML_UI_ButtonArrow_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "PreConstruct");

	Params::SCML_UI_ButtonArrow_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USCML_UI_ButtonArrow_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "OnMouseLeave");

	Params::SCML_UI_ButtonArrow_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USCML_UI_ButtonArrow_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "OnMouseEnter");

	Params::SCML_UI_ButtonArrow_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply USCML_UI_ButtonArrow_C::OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "OnMouseButtonUp");

	Params::SCML_UI_ButtonArrow_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply USCML_UI_ButtonArrow_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "OnMouseButtonDown");

	Params::SCML_UI_ButtonArrow_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.OnMouseButtonDoubleClick
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 InMyGeometry                                           (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             InMouseEvent                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply USCML_UI_ButtonArrow_C::OnMouseButtonDoubleClick(const struct FGeometry& InMyGeometry, const struct FPointerEvent& InMouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "OnMouseButtonDoubleClick");

	Params::SCML_UI_ButtonArrow_C_OnMouseButtonDoubleClick Parms{};

	Parms.InMyGeometry = std::move(InMyGeometry);
	Parms.InMouseEvent = std::move(InMouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USCML_UI_ButtonArrow_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SCML_UI_ButtonArrow.SCML_UI_ButtonArrow_C.ExecuteUbergraph_SCML_UI_ButtonArrow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USCML_UI_ButtonArrow_C::ExecuteUbergraph_SCML_UI_ButtonArrow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SCML_UI_ButtonArrow_C", "ExecuteUbergraph_SCML_UI_ButtonArrow");

	Params::SCML_UI_ButtonArrow_C_ExecuteUbergraph_SCML_UI_ButtonArrow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

