#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UPI_ObjModData

#include "Basic.hpp"

#include "UPI_KeySet_structs.hpp"
#include "UPI_KeyData_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UPI_ObjModData.UPI_ObjModData_C
// 0x0088 (0x00B0 - 0x0028)
class UUPI_ObjModData_C final : public UObject
{
public:
	class UObject*                                CallbackObject;                                    // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FString                                 ModName;                                           // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 ModCreator;                                        // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TMap<struct FUPI_KeySet, struct FUPI_KeyData> InputRegister;                                     // 0x0050(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TScriptInterface<class IUPI_InterfaceFunctions_C> CallbackInterface;                             // 0x00A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UPI_ObjModData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UPI_ObjModData_C")
	}
	static class UUPI_ObjModData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUPI_ObjModData_C>();
	}
};
DUMPER7_ASSERTS_UUPI_ObjModData_C;

}

