#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ingame_PlayerGauge_ThworObjectNone

#include "Basic.hpp"

#include "E_PalUIThrowObjectNoneMessageType_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Ingame_PlayerGauge_ThworObjectNone.WBP_Ingame_PlayerGauge_ThworObjectNone_C
// 0x0060 (0x02D8 - 0x0278)
class UWBP_Ingame_PlayerGauge_ThworObjectNone_C final : public UUserWidget
{
public:
	class UBP_PalTextBlock_C*                     Text_Main;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<E_PalUIThrowObjectNoneMessageType, struct FDataTableRowHandle> MsgIDMap;                    // 0x0280(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FTimerHandle                           HideTimerHandle;                                   // 0x02D0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Display(double DisplayTime);
	void Hide();
	void OnTimer_Hide();
	void SetDisplayMode(E_PalUIThrowObjectNoneMessageType DisplayType);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Ingame_PlayerGauge_ThworObjectNone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Ingame_PlayerGauge_ThworObjectNone_C")
	}
	static class UWBP_Ingame_PlayerGauge_ThworObjectNone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Ingame_PlayerGauge_ThworObjectNone_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Ingame_PlayerGauge_ThworObjectNone_C;

}

