#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameCompass_WarpPoint

#include "Basic.hpp"

#include "WBP_CompassIconBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_IngameCompass_WarpPoint.WBP_IngameCompass_WarpPoint_C
// 0x0010 (0x04A8 - 0x0498)
class UWBP_IngameCompass_WarpPoint_C final : public UWBP_CompassIconBase_C
{
public:
	class UImage*                                 Image_Icon;                                        // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_Length;                                       // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetDistanceText(double Length);
	void SetupTexture(TSoftObjectPtr<class UTexture2D> SoftTexture);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_IngameCompass_WarpPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_IngameCompass_WarpPoint_C")
	}
	static class UWBP_IngameCompass_WarpPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_IngameCompass_WarpPoint_C>();
	}
};
DUMPER7_ASSERTS_UWBP_IngameCompass_WarpPoint_C;

}

