#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Trading_Item

#include "Basic.hpp"

#include "WBP_Trading_Item_classes.hpp"
#include "WBP_Trading_Item_parameters.hpp"


namespace SDK
{

// Function WBP_Trading_Item.WBP_Trading_Item_C.AllGet
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::AllGet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "AllGet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_8_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_8_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_8_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_8_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_9_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_9_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_9_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_PalEditableTextBox_ProductNum_K2Node_ComponentBoundEvent_9_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_CommonButton__K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_CommonButton__K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_CommonButton__K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_CommonButton_Cancel_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_CommonButton_Cancel_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_CommonButton_Cancel_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_16_OnClickedTargetContainerSortButton__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_16_OnClickedTargetContainerSortButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_16_OnClickedTargetContainerSortButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_17_OnClickedCloseButton__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_17_OnClickedCloseButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_17_OnClickedCloseButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_20_OnHoveredInventorySlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     SlotButton                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_20_OnHoveredInventorySlot__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* SlotButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_20_OnHoveredInventorySlot__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_20_OnHoveredInventorySlot__DelegateSignature Parms{};

	Parms.SlotButton = SlotButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_21_OnHoveredTargetContainerSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     SlotButton                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_21_OnHoveredTargetContainerSlot__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* SlotButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_21_OnHoveredTargetContainerSlot__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_21_OnHoveredTargetContainerSlot__DelegateSignature Parms{};

	Parms.SlotButton = SlotButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_6_OnClickedInventorySortButton__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_6_OnClickedInventorySortButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_6_OnClickedInventorySortButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_7_OnClickedQuickMoveButton__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_7_OnClickedQuickMoveButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_IngameMenu_Chest_K2Node_ComponentBoundEvent_7_OnClickedQuickMoveButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_ItemSlot_Cost_K2Node_ComponentBoundEvent_5_OnClickedButton__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_ItemSlot_Cost_K2Node_ComponentBoundEvent_5_OnClickedButton__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* Widget, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_ItemSlot_Cost_K2Node_ComponentBoundEvent_5_OnClickedButton__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_ItemSlot_Cost_K2Node_ComponentBoundEvent_5_OnClickedButton__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_ItemSlot_Product_K2Node_ComponentBoundEvent_2_OnClickedButton__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_ItemSlot_Product_K2Node_ComponentBoundEvent_2_OnClickedButton__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* Widget, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_ItemSlot_Product_K2Node_ComponentBoundEvent_2_OnClickedButton__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_ItemSlot_Product_K2Node_ComponentBoundEvent_2_OnClickedButton__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_Menu_btn_K2Node_ComponentBoundEvent_18_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_Menu_btn_K2Node_ComponentBoundEvent_18_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_Menu_btn_K2Node_ComponentBoundEvent_18_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Lock_CheckBox_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Lock_CheckBox_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Lock_CheckBox_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Lock_CheckBox_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_1_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_1_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_1_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_1_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_1_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_1_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_1_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_1_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Sort_TargetContainer_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Sort_TargetContainer_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Sort_TargetContainer_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Item_C_BndEvt__WBP_Trading_Item_WBP_PalInvisibleButton_Sort_TargetContainer_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Trading_Item_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.DelayUnhoverStorePanel
// (BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::DelayUnhoverStorePanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "DelayUnhoverStorePanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Trading_Item_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Enable Cost Select
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::Enable_Cost_Select()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Enable Cost Select");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Enable Product Select
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::Enable_Product_Select(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Enable Product Select");

	Params::WBP_Trading_Item_C_Enable_Product_Select Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.ExecuteUbergraph_WBP_Trading_Item
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::ExecuteUbergraph_WBP_Trading_Item(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "ExecuteUbergraph_WBP_Trading_Item");

	Params::WBP_Trading_Item_C_ExecuteUbergraph_WBP_Trading_Item Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.FocusLeft
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::FocusLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "FocusLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.FocusRight
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::FocusRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "FocusRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.FocusToStoreManage
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::FocusToStoreManage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "FocusToStoreManage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.On Store Content Updated
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalItemContainer*                ItemContainer                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::On_Store_Content_Updated(class UPalItemContainer* ItemContainer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "On Store Content Updated");

	Params::WBP_Trading_Item_C_On_Store_Content_Updated Parms{};

	Parms.ItemContainer = ItemContainer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnCancelAction
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::OnCancelAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnCancelAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnClickedAnyProductSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Slot_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnClickedAnyProductSlot(class UWBP_PalItemSlotButtonBase_C* Slot_0, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnClickedAnyProductSlot");

	Params::WBP_Trading_Item_C_OnClickedAnyProductSlot Parms{};

	Parms.Slot_0 = Slot_0;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnClickedCostSelectSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             StaticItemId                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnClickedCostSelectSlot(class FName StaticItemId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnClickedCostSelectSlot");

	Params::WBP_Trading_Item_C_OnClickedCostSelectSlot Parms{};

	Parms.StaticItemId = StaticItemId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnClickedRemoveTradeButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TradeIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnClickedRemoveTradeButton(int32 TradeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnClickedRemoveTradeButton");

	Params::WBP_Trading_Item_C_OnClickedRemoveTradeButton Parms{};

	Parms.TradeIndex = TradeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Trading_Item_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnPrivateLockChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGuid&                     LockPlayerUId                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnPrivateLockChanged(const struct FGuid& LockPlayerUId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnPrivateLockChanged");

	Params::WBP_Trading_Item_C_OnPrivateLockChanged Parms{};

	Parms.LockPlayerUId = std::move(LockPlayerUId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnSetup
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::OnSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnStoreSlotHovered
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnStoreSlotHovered(class UWBP_PalItemSlotButtonBase_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnStoreSlotHovered");

	Params::WBP_Trading_Item_C_OnStoreSlotHovered Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnStoreSlotUnhovered
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnStoreSlotUnhovered(class UWBP_PalItemSlotButtonBase_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnStoreSlotUnhovered");

	Params::WBP_Trading_Item_C_OnStoreSlotUnhovered Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnTradeEdit
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnTradeEdit(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnTradeEdit");

	Params::WBP_Trading_Item_C_OnTradeEdit Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnTradeHovered
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TradeIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnTradeHovered(int32 TradeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnTradeHovered");

	Params::WBP_Trading_Item_C_OnTradeHovered Parms{};

	Parms.TradeIndex = TradeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.OnTradeUnhovered
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TradeIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::OnTradeUnhovered(int32 TradeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "OnTradeUnhovered");

	Params::WBP_Trading_Item_C_OnTradeUnhovered Parms{};

	Parms.TradeIndex = TradeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Refill
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::Refill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Refill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.SetCostSettingNum
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewNum                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::SetCostSettingNum(int32 NewNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "SetCostSettingNum");

	Params::WBP_Trading_Item_C_SetCostSettingNum Parms{};

	Parms.NewNum = NewNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.SetProductSettingNum
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewNum                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::SetProductSettingNum(int32 NewNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "SetProductSettingNum");

	Params::WBP_Trading_Item_C_SetProductSettingNum Parms{};

	Parms.NewNum = NewNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Sort
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::Sort()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Sort");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.SwitchSellPanel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ToSellList                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::SwitchSellPanel(bool ToSellList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "SwitchSellPanel");

	Params::WBP_Trading_Item_C_SwitchSellPanel Parms{};

	Parms.ToSellList = ToSellList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.SwitchSlotPanelHoverDisplay
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHover                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::SwitchSlotPanelHoverDisplay(bool IsHover)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "SwitchSlotPanelHoverDisplay");

	Params::WBP_Trading_Item_C_SwitchSlotPanelHoverDisplay Parms{};

	Parms.IsHover = IsHover;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.SwitchStoragePanelVisibility
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Item_C::SwitchStoragePanelVisibility(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "SwitchStoragePanelVisibility");

	Params::WBP_Trading_Item_C_SwitchStoragePanelVisibility Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Toggle Private Lock
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::Toggle_Private_Lock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Toggle Private Lock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.ToSellListPanel
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::ToSellListPanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "ToSellListPanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.ToSetSellPanel
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::ToSetSellPanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "ToSetSellPanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.Update Sell List
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::Update_Sell_List()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "Update Sell List");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.ValidateCurrentTradeInfo
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Item_C::ValidateCurrentTradeInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "ValidateCurrentTradeInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Item.WBP_Trading_Item_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Trading_Item_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Item_C", "BP_GetDesiredFocusTarget");

	Params::WBP_Trading_Item_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

