#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameConstruction_Dismantling

#include "Basic.hpp"

#include "WBP_IngameConstruction_Dismantling_classes.hpp"
#include "WBP_IngameConstruction_Dismantling_parameters.hpp"


namespace SDK
{

// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.UpdateBuildingLimit
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalUIDismantlingModel*           Model                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameConstruction_Dismantling_C::UpdateBuildingLimit(class UPalUIDismantlingModel* Model)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "UpdateBuildingLimit");

	Params::WBP_IngameConstruction_Dismantling_C_UpdateBuildingLimit Parms{};

	Parms.Model = Model;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.SetWarningText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_IngameConstruction_Dismantling_C::SetWarningText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "SetWarningText");

	Params::WBP_IngameConstruction_Dismantling_C_SetWarningText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.SetupKeyGuide
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_IngameConstruction_Dismantling_C::SetupKeyGuide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "SetupKeyGuide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPalBuildObjectData&       inBuildObjectData                                      (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_IngameConstruction_Dismantling_C::Setup(const struct FPalBuildObjectData& inBuildObjectData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "Setup");

	Params::WBP_IngameConstruction_Dismantling_C_Setup Parms{};

	Parms.inBuildObjectData = std::move(inBuildObjectData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.SetMaterial
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             StaticItemId                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ItemCount                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameConstruction_Dismantling_C::SetMaterial(int32 Index_0, class FName StaticItemId, int32 ItemCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "SetMaterial");

	Params::WBP_IngameConstruction_Dismantling_C_SetMaterial Parms{};

	Parms.Index_0 = Index_0;
	Parms.StaticItemId = StaticItemId;
	Parms.ItemCount = ItemCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.SetEnableWarning
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnable                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameConstruction_Dismantling_C::SetEnableWarning(bool IsEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "SetEnableWarning");

	Params::WBP_IngameConstruction_Dismantling_C_SetEnableWarning Parms{};

	Parms.IsEnable = IsEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.SetDismantleObjectName
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InName                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_IngameConstruction_Dismantling_C::SetDismantleObjectName(const class FText& InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "SetDismantleObjectName");

	Params::WBP_IngameConstruction_Dismantling_C_SetDismantleObjectName Parms{};

	Parms.InName = std::move(InName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.ResetAllUI
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_IngameConstruction_Dismantling_C::ResetAllUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "ResetAllUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_IngameConstruction_Dismantling_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.InitUI
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_IngameConstruction_Dismantling_C::InitUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "InitUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.GetBuildingWarningType
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UPalUIDismantlingModel*           Model                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EPalBuildingNumWarningType*             NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameConstruction_Dismantling_C::GetBuildingWarningType(class UPalUIDismantlingModel* Model, EPalBuildingNumWarningType* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "GetBuildingWarningType");

	Params::WBP_IngameConstruction_Dismantling_C_GetBuildingWarningType Parms{};

	Parms.Model = Model;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.ExecuteUbergraph_WBP_IngameConstruction_Dismantling
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameConstruction_Dismantling_C::ExecuteUbergraph_WBP_IngameConstruction_Dismantling(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "ExecuteUbergraph_WBP_IngameConstruction_Dismantling");

	Params::WBP_IngameConstruction_Dismantling_C_ExecuteUbergraph_WBP_IngameConstruction_Dismantling Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameConstruction_Dismantling.WBP_IngameConstruction_Dismantling_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_IngameConstruction_Dismantling_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameConstruction_Dismantling_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

